config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :requests, only: [:new, :create]
  resources :feedbacks, only: [:new, :create]

  get 'thank_you', to: 'pages#thank_you'
  get 'requests', to: 'requests#new'

  root to: 'requests#new'
end

app/models/admin/admin_user.rb
class Admin::AdminUser < AdminUser
end

app/models/admin/feedback.rb
class Admin::Feedback < Feedback
  include Recent
end

app/models/admin/request.rb
class Admin::Request < Request
  include Recent
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :requests, dependent: :nullify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/recent.rb
module Recent
  extend ActiveSupport::Concern

  module ClassMethods
    def recent(count)
      order(created_at: :desc).first(count)
    end
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :request

  validates :details, :rate, presence: true
  validates :rate, numericality: { greater_than: 0, less_than_or_equal_to: 5 }

  def request=(request)
    self.attributes = request.slice(
      :customer_name,
      :customer_email,
      :project_name,
      :feature_name
    )

    super
  end

  def customer_name=(name)
    super(name.to_s.titleize)
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :admin_user
  has_many :feedbacks, dependent: :nullify

  validates :project_name, :feature_name, :customer_name, :customer_email, presence: true
  validates :customer_email, format: { with: /.+@.+\..+/ }

  class << self
    def uid
      loop do
        code = RandomCode.numeric(8)
        break code unless exists?(uid: code)
      end
    end
  end

  def customer_name=(name)
    super(name.to_s.titleize)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    '/'
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < InheritedResources::Base
  attr_reader :feedback

  def new
    @feedback = Feedback.new(request: uid_request)
  end

  def create
    feedback_creator = FeedbackCreator.new(feedback_params)

    if feedback_creator.create(uid_request)
      redirect_to thank_you_path
    else
      @feedback = feedback_creator.feedback
      render :new, uid: uid
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:rate, :details)
  end

  def uid
    params[:uid].presence || not_found
  end

  def uid_request
    Request.find_by!(uid: uid)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/requests_controller.rb
class RequestsController < InheritedResources::Base
  attr_reader :req

  before_action :authenticate_admin_user!, only: [:new, :create]

  def new
    @req = Request.new
  end

  def create
    creator = RequestCreator.new(request_params)
    @req = creator.request

    if creator.create(current_admin_user)
      notice = "Request sucessfully sent (#{new_feedback_url(uid: req.uid)})"
      redirect_to new_request_path, flash: { notice: notice }
    else
      render :new
    end
  end

  private

  def request_params
    params.require(:request).permit(:project_name, :feature_name, :customer_name, :customer_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/feedbacks/_form.html.slim
= form_for @feedback do |f|
  = hidden_field :nil, nil, value: @feedback.request.uid, name: :uid, id: :uid

  - @feedback.errors.full_messages.each do |message|
    .alert.alert-danger
      span.sr-only Error:
      = message

  label[for="project_name"] Project Name
  = f.text_field :project_name, class: 'form-control', disabled: true

  label[for="feature_name"] Feature Name
  = f.text_field :feature_name, class: 'form-control', disabled: true

  label[for="rate"] Rate
  = f.number_field :rate, class: 'form-control', placeholder: '1 - 5', min: 1, max: 5, value: 5

  label[for="details"] Details
  = f.text_area :details, class: 'form-control'

  = f.submit class: 'btn btn-default', value: 'Send Feedback'

app/views/feedbacks/new.html.slim
.page-header
  h1 New feedback

== render 'form'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    title Feedbacks
    = csrf_meta_tags
    link[rel="apple-touch-icon" sizes="57x57" href="https://shakuro.com/apple-touch-icon-57x57.png"]
    link[rel="apple-touch-icon" sizes="60x60" href="https://shakuro.com/apple-touch-icon-60x60.png"]
    link[rel="apple-touch-icon" sizes="72x72" href="https://shakuro.com/apple-touch-icon-72x72.png"]
    link[rel="apple-touch-icon" sizes="76x76" href="https://shakuro.com/apple-touch-icon-76x76.png"]
    link[rel="apple-touch-icon" sizes="114x114" href="https://shakuro.com/apple-touch-icon-114x114.png"]
    link[rel="apple-touch-icon" sizes="120x120" href="https://shakuro.com/apple-touch-icon-120x120.png"]
    link[rel="apple-touch-icon" sizes="144x144" href="https://shakuro.com/apple-touch-icon-144x144.png"]
    link[rel="apple-touch-icon" sizes="152x152" href="https://shakuro.com/apple-touch-icon-152x152.png"]
    link[rel="apple-touch-icon" sizes="180x180" href="https://shakuro.com/apple-touch-icon-180x180.png"]
    link[rel="icon" type="image/png" href="https://shakuro.com/favicon-32x32.png" sizes="32x32"]
    link[rel="icon" type="image/png" href="https://shakuro.com/favicon-194x194.png" sizes="194x194"]
    link[rel="icon" type="image/png" href="https://shakuro.com/favicon-96x96.png" sizes="96x96"]
    link[rel="icon" type="image/png" href="https://shakuro.com/android-chrome-192x192.png" sizes="192x192"]
    link[rel="icon" type="image/png" href="https://shakuro.com/favicon-16x16.png" sizes="16x16"]

    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous"]

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      header.header
        .content
          .row
            .col-sm-11
              .logo
                a.site-logo[href="https://shakuro.com"] shakuro
            .col-sm-1
              .logout
                - if admin_user_signed_in?
                  = link_to 'Log out', destroy_admin_user_session_path

      .row
        - if notice.present?
          p.alert.alert-success= notice
        - if alert.present?
          p.alert.alert-danger= alert

      = yield

app/views/pages/thank_you.html.slim
.page-header
  h1 Thank you for cooperation.
  h4 We really apreciate your input and will do our best to consider your comments next time

app/views/requests/_form.html.slim
= form_for @req do |f|
  - @req.errors.full_messages.each do |message|
    .alert.alert-danger
      span.sr-only Error:
      = message

  label[for="project_name"] Project Name
  = f.text_field :project_name, class: 'form-control'

  label[for="feature_name"] Feature Name
  = f.text_field :feature_name, class: 'form-control'

  label[for="customer_name"] Customer Name
  = f.text_field :customer_name, class: 'form-control'

  label[for="customer_email"] Customer Email
  = f.text_field :customer_email, class: 'form-control', placeholder: 'customer@email.com'

  = f.submit class: 'btn btn-default', value: 'Send Request'

app/views/requests/new.html.slim
.page-header
  h1 New request

== render 'form'